CREATE TABLE IF NOT EXISTS post_tests (
  post_test_id INT PRIMARY KEY AUTO_INCREMENT,
  booking_id INT NOT NULL,
  tutor_id INT NOT NULL,
  student_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  subject_id INT,
  subject_name VARCHAR(255),
  total_questions INT DEFAULT 0,
  time_limit INT DEFAULT 30,
  passing_score INT DEFAULT 70,
  status ENUM('draft', 'published', 'completed') DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  published_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  FOREIGN KEY (tutor_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(subject_id) ON DELETE SET NULL,
  INDEX idx_booking_id (booking_id),
  INDEX idx_tutor_id (tutor_id),
  INDEX idx_student_id (student_id),
  INDEX idx_status (status)
);